### ISSUE TITLE
"Tap view"

### ISSUE THREAD

**Issue by Apisov** [jlmd/AnimatedCircleLoadingView#1]
Why are you implemented circle that represent interaction of user with watch?
I think it's totally redundant.
Anyway - nice work. But removing this circle will be absolutely right choice.

**Comment by jlmd** [comment]
Well, I thought that the grey circle was a component of the view, that's why I've added it.
Anyway, I think that it doesn't look bad with that circle, so I think I will let it as a view component.
Thanks for the recommendation!
