### ISSUE TITLE
Failed to resolve :com.github.jlmd:AnimatedCircleLoadingView:1.1.5

### ISSUE THREAD

**Issue by abhishobhit** [jlmd/AnimatedCircleLoadingView#14]
I have Same problem , I have added it to repository but its not working.

    repositories {
        jcenter()
        maven {
            url "http://dl.bintray.com/jlmd/maven"
        }
    }

**Comment by jlmd** [comment]
Are you adding it in allprojects? 

	allprojects {
	  repositories {
	    maven {
	      url "http://dl.bintray.com/jlmd/maven"
	    }
	    jcenter()
	  }
	}

**Comment by abhishobhit** [comment]
Yes I have added in allprojects..

**Comment by jlmd** [comment]
Well, I've just test it and it's working.

**Comment by sharathp** [comment]
having same issue:

```Error:Could not find com.github.jkwiecien:EasyImage:1.1.5.```

**Comment by jlmd** [comment]
Uhm, it's not related to my library. You have to ask it to the owner of _com.github.jkwiecien:EasyImage_

**Comment by sharathp** [comment]
@jlmd - apologize, yes, my bad, it works, thanks!
