### ISSUE TITLE
Error: Attribute "textColor" has already been defined

### ISSUE THREAD

**Issue by dmsherazi** [jlmd/AnimatedCircleLoadingView#15]
It would be great if the attributes are prefixed to avoid conflicts with other libs

**Comment by Elappnano** [comment]
I also have this error. how should we fix this?

**Comment by dmsherazi** [comment]
you can import the source code in your project and in attributes rename the textColor attribute to something that's not being used any where else.

**Comment by jlmd** [comment]
it's solved in version 1.1.6 (8b9ef3a784aa09b80cd8eac29709e1ae869f3bc0)
