### ISSUE TITLE
Please remove android:label attribute from AndroidManifest

### ISSUE THREAD

**Issue by filipebezerra** [jlmd/AnimatedCircleLoadingView#18]
Thanks for you awesome work.

Can you remove the attribute `android:label` from your `AndroidManifest`, in fact you don't need one. When you specify this attribute it's hard to apps change their `android:label` in build time, as you can note in the error above:

Error:Execution failed for task ':app:processProdDebugManifest'.

> Manifest merger failed : Attribute application@label value=(YVD) from AndroidManifest.xml:21:9-44
>     is also present at [com.github.jlmd:AnimatedCircleLoadingView:1.1.5] AndroidManifest.xml:13:9-41 value=(@string/app_name).
>     Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:18:5-143:19 to override.

**Comment by jlmd** [comment]
There is not `android:label` attribute in the `AndroidManifest` from the library. Maybe you are using the sample app as dependency instead of the library.
