### ISSUE TITLE
Gradle fail to resolve:com.github.jlmd:AnimatedCircleLoadingView:1.1

### ISSUE THREAD

**Issue by baibig** [jlmd/AnimatedCircleLoadingView#2]
Gradle in my android studio failed to resolve AnimatedCircleLoadingView, and there is no search result for AnimatedCircleLoadingView in maven central repository .Why this happened?

**Comment by jlmd** [comment]
It's because the library isn't in maven central. It's in bintray. You have to add the repository:

repositories {
  maven {
    url "http://dl.bintray.com/jlmd/maven"
  }
}
