### ISSUE TITLE
Error: Failed to resolve: com.github.animatedcircleloadingview:1.1.5

### ISSUE THREAD

**Issue by AerWyn81** [jlmd/AnimatedCircleLoadingView#23]
Hi,

All is in the title, I'm trying to use your library, so I added your library in my build.gradle and I got this error.
`compile 'com.github.jlmd:AnimatedCircleLoadingView:1.1.5@aar'`
AerWyn81

**Comment by hichamkazan** [comment]
You should add to your project build.gradle this

```
maven {
            url "http://dl.bintray.com/jlmd/maven"
        }

```
under allprojects >> repositories
