### ISSUE TITLE
Percent text color

### ISSUE THREAD

**Issue by Siddounet** [jlmd/AnimatedCircleLoadingView#3]
Hi,

Is it possible to add a setter to `PercentIndicatorView` to get the TextView and set some colors/attrs?
`public void setTextColor(int color)
{
   setTextColor(color);
}`
...

And ofc a setter in `AnimatedCircleLoadingView` ?

Or just a getter on `percentIndicatorView` ?

Thx,
Bastien.

**Comment by Siddounet** [comment]
Pull request added. Please check-it.
Thx,
Bastien.

**Comment by fcouceiro** [comment]
Would be nice to have tint colors on the checked_mark and failure_mark!

**Comment by hebing521** [comment]
Are u fixedd?

**Comment by jlmd** [comment]
Added in version 1.1.3
Thanks @Siddounet
