### ISSUE TITLE
gradle

### ISSUE THREAD

**Issue by d7coders** [jlmd/AnimatedCircleLoadingView#5]
gradle not work

Error:(51, 13) Failed to resolve: com.github.jlmd:AnimatedCircleLoadingView:1.1.2

**Comment by jlmd** [comment]
It's because the library isn't in maven central. It's in bintray. You have to add the repository:

repositories {
maven {
url "http://dl.bintray.com/jlmd/maven"
}
}

**Comment by praveensleeps** [comment]
is the new update working in 4.3 devices?

**Comment by jlmd** [comment]
yes, it should work
