### ISSUE TITLE
require finish callback 

### ISSUE THREAD

**Issue by riontech-xten** [jlmd/AnimatedCircleLoadingView#9]
no callback of finish view after finished the animation.

**Comment by wardellchandler** [comment]
Bump. Without the finish callback, it's hard to enjoy the finish animation because you likely want to show a view as soon as the animation is finished.

**Comment by fcouceiro** [comment]
As soon as @jlmd merges my previous PR, I'll be submitting a new one, including this callback and antialias rendering, for discussion ;)

**Comment by jlmd** [comment]
Thanks @fcouceiro but I have almost finished the callback feature. 
Antialias rendering would be nice!

**Comment by fcouceiro** [comment]
Cool! It's just a matter of setting the flag. I'll merge the commit in my PR.

**Comment by jlmd** [comment]
Added animation listener, mark tint and antialias rendering in version 1.1.4
Thanks @fcouceiro for the PRs

**Comment by fcouceiro** [comment]
You're welcome ;)

**Comment by fcouceiro** [comment]
@jlmd Just updated to the new version. One thing I find useful is having a way to check if the loading was successful or not in the callback. In the way it is implemented we only get the chance to know that the loading is finished. Or do we have any other variable that we can check?

**Comment by jlmd** [comment]
Yes, that's true. I should add a parameter to the callback indicating if the loading was successful.
I will do it soon.
Thanks!

**Comment by josephlam1984** [comment]
Great library - any update on attaching a success flag to the callback, Jim?  Thanks!

**Comment by jlmd** [comment]
I've just added a success flag in onAnimationEnd listener.
It's released in version 1.1.5.
